#ifndef X1COIN_CHAINPARAMSSEEDS_H
#define X1COIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the x1coin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x42,0x5e,0x73,0x50,0x3b,0x9a,
    0x01,0x04,0xad,0xd4,0xe0,0x43,0x3b,0x9a,
    0x01,0x04,0x2e,0xfa,0xe5,0xa6,0x3b,0x9a,
};

static const uint8_t chainparams_seed_test[] = {
};
#endif // X1COIN_CHAINPARAMSSEEDS_H
